<?php

/**
 * 
 *
 * @version $Id$
 * @copyright 2003 
 **/
	define('INSTALL_DIRECTORY', 'C:\\Archivos de programa\\EasyPHP1-7\\www\\');
	define('INSTALL_IS_WINDOWS',TRUE);
	define('SMARTY_DIRECTORY', INSTALL_DIRECTORY . 'includes\\smarty\\');
	define('ADODB_DIRECTORY',INSTALL_DIRECTORY . 'includes\\adodb\\');
	define('USER','root');
	define('PASS','sta3war2');
	define('BD_NAME','facturaphp');
	define('IP_MYSQL','127.0.0.1');
	define('BD_PREFIX','');
	define('BBDD_TYPE','mysql');
	
?>